
experiment: 
    name: "ProxyNCA-v2"
    max_epochs: 50
    gpus: 1

dataset:
    name: "Cars196"
    root: "/mnt/vol_b/cars/" 

# dataset:
#     name: "UMPC-Food101"
#     root: "/mnt/vol_b/UPMC_Food101/images/" 
#     classes_filename: "/home/ubuntu/few-shot-metric-learning/src/UMPC-G20.txt"

# dataset:
#     name: "UMPC-G20"
#     root: "/mnt/vol_b/images/" 
#     classes_filename: "/home/ubuntu/few-shot-metric-learning/src/UMPC-G20.txt"


model:
    embedding_size: 64
    backbone: "inception_v3"
    pooling: "max"
    pretrained: True
    lr_backbone: 0.01
    weight_decay_backbone: 0.0
    lr_embedding: 0.001
    weight_decay_embedding: 0.0
    lr: 0.001
    weight_decay_proxynca: 0.0
    scaling_x: 3.0
    scaling_p: 3.0
    smoothing_const: 0.1
    batch_size: 32
    vis_dim: "(2,3)"
    gradient_clip_val: 2.0
